### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by hlsafin** [pocokhc/agent57#7]
![image](https://user-images.githubusercontent.com/36808133/112483734-b1cf0780-8d4f-11eb-8c56-58ce5569f4cd.png)

getting 
AttributeError: 'NoneType' object has no attribute 'terminate'
when running python atari_pong.py

**Comment by pocokhc** [comment]
I don't know the cause of the error, but the code that caused the error is the code that prevents the process from remaining when the program ends.(This is just in case)
Therefore, even if an error occurs, there is no problem in operation.

---
エラーの原因は分かりませんが、エラーが出たコードはプログラム終了時にプロセスが残るのを回避するためのコードになります。(念のためのコードです)
ですので、エラーが出たとしても動作に支障はありません。

**Comment by hlsafin** [comment]
So when you run atari_pong.py you don't run into any issues at all? Can you tell me your spec, this might be the issue?

**Comment by pocokhc** [comment]
The environment has already been destroyed, and it took time to create the environment again.
I confirmed the same error.

I think it's probably due to the version difference.

```
>pip list
Package                  Version
------------------------ -------------------
(snip)
Keras                    2.4.3
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.2
(snip)
tensorflow-gpu           2.4.1
tensorflow-gpu-estimator 2.1.0
(snip)

↓↓↓

(snip)
--- start ---
'Ctrl + C' is stop.
GPU: enable
2021-04-02 09:02:46.734039: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following 
CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 09:02:46.880289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-02 09:02:46.890618: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 09:02:46.894827: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 09:02:46.899011: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 09:02:46.903468: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:02:46.908167: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:02:46.912468: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:02:46.916746: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 09:02:46.921250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 09:02:46.925937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-02 09:02:47.386811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 09:02:47.391924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-04-02 09:02:47.394645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-04-02 09:02:47.397679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2094 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-04-02 09:02:47.430442: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "e:\data\GitHub2\agent57\examples\..\agent\agent57.py", line 291, in _train
    self.learner_ps.start()
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'

done, took 0.011 seconds
done, took 0.000 minutes
learner end timeout.
2021-04-02 09:02:47.788047: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
pygame 2.0.1 (SDL 2.0.14, Python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
2021-04-02 09:02:49.509220: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 09:02:49.515045: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-04-02 09:02:49.535814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-02 09:02:49.546576: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 09:02:49.556904: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 09:02:49.562461: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 09:02:49.569940: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:02:49.576424: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:02:49.584593: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:02:49.592087: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 09:02:49.597454: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 09:02:49.602274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Exception ignored in: <function Agent57.__del__ at 0x00000216BF870DC8>
Traceback (most recent call last):
  File "e:\data\GitHub2\agent57\examples\..\agent\agent57.py", line 215, in __del__
    self.learner_ps.terminate()
  File "C:\Users\poco\Anaconda3\envs\gpu\lib\multiprocessing\process.py", line 124, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

I changed the version below.

```
> pip install -U keras==2.3.1
> pip install -U tensorflow-gpu==2.1.0

↓↓↓

(snip)
--- start ---
'Ctrl + C' is stop.
GPU: enable
Using TensorFlow backend.
2021-04-02 09:09:22.848687: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Using TensorFlow backend.
2021-04-02 09:09:22.907273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
pygame 2.0.1 (SDL 2.0.14, Python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame 2.0.1 (SDL 2.0.14, Python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
2021-04-02 09:09:24.466450: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-04-02 09:09:24.488038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-02 09:09:24.499460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-04-02 09:09:24.507308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-04-02 09:09:24.514458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:09:24.519710: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:09:24.527528: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:09:24.533677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-04-02 09:09:24.541037: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully 2o0p2e1n-e0d4 -d0y2n a0m9i:c0 9l:i2b4r.a5r4y3 8n1v0c:u dIa .tdelnls
orflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-04-02 09:09:24.549665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-04-02 09:09:24.562658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapabilit2y0:2 16-.014
-co0reC2l o0ck9:: 019.:2740.8556G8H9z9 3c:o rIe Ctoeunnsto:r 9 dfleovwi/cceoMreem/oprlyaStifzoer:m /3c.p0u0_GfieBa tduervei_cgeuMaermdo.rcycB:a1n4d2w]i dYoturh C:P U su17ppor8t.s9 9inGsitBr/usc
ti2o0n2s1 -t0h4a-t0 2t h0i9s: 0T9e:n2s4o.r5F7l5o9w4 9b:i nIar yt ewnasso rnfolto wc/osmtprielaemd_ etxoe cuusteo:r /ApVlXa2t
form/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-04-02 09:09:24.584914: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-04-02 09:09:24.592381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:09:24.597753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:09:24.606188: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:09:24.613612: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-04-02 09:09:24.623872: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-04-02 09:09:24.628994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-04-02 09:09:24.647919: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-04-02 09:09:24.711090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-02 09:09:24.721577: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-04-02 09:09:24.726516: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-04-02 09:09:24.731204: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:09:24.735744: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:09:24.741348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:09:24.745988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-04-02 09:09:24.754230: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-04-02 09:09:24.763002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-04-02 09:09:24.790245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-02 09:09:24.801739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-04-02 09:09:24.806954: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-04-02 09:09:24.813111: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-04-02 09:09:24.818262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-04-02 09:09:24.823401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 09:09:24.828440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-04-02 09:09:24.833166: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-04-02 09:09:24.837913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-04-02 09:09:25.187522: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 09:09:25.193155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2021-04-02 09:09:25.196069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2021-04-02 09:09:25.199325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2102 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-04-02 09:09:25.256067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 09:09:25.261671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2021-04-02 09:09:25.265093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2021-04-02 09:09:25.268716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2102 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Actor0 Start!
Learner Start!
2021-04-02 09:10:23.806618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-04-02 09:10:24.022882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-04-02 09:10:24.724898: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. This message will be only logged once.
actor0   Train 0, Time: 1.05m, Reward    :   -5.00 -   -3.00 (ave:   -4.75), nb_steps: 2743
weight save, ave reward:-5.0000
learner  Train 0, Time: 1.00m, TestReward:   -5.00 -   -5.00 (ave:   -5.00)

(snip)

```

Just in case, I will write down the specifications on the PC side.

OS: Windows 10 Pro
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Memory: 48.0 GB
GPU: NVIDIA GeForce GTX 1060 3GB
