### ISSUE TITLE
Running on lower hardware?

### ISSUE THREAD

**Issue by robjlyons** [pocokhc/agent57#9]
Hi, 

I'm trying to run the Atari version of this on a quad-core and Geforce GTX1060 (3gb)

Are there any particular settings I can change to stop memory errors?

Below is the full readout I get, most are TensorFlow logs but right at the bottom is the memory errors.

Thanks,

Using TensorFlow backend.
2021-11-05 09:29:18.871524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
2021-11-05 09:29:21.783397: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-11-05 09:29:21.803039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:21.803180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:21.809795: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:21.813410: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:21.816551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:21.821155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:21.824652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:21.834075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:21.834969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
action_space      : Discrete(6)
observation_space : Box(210, 160, 3)
reward_range      : (-inf, inf)
2021-11-05 09:29:22.743785: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-11-05 09:29:22.744232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:22.744720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:22.745569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:22.745898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:22.746511: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:22.747152: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:22.747674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:22.748245: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:22.750397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-11-05 09:29:23.346478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-05 09:29:23.346643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2021-11-05 09:29:23.349156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2021-11-05 09:29:23.351773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2102 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
nb_time  : 1080.00m
nb_trains: 1750000
--- start ---
'Ctrl + C' is stop.
GPU: enable
Using TensorFlow backend.
2021-11-05 09:29:23.829305: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Using TensorFlow backend.
2021-11-05 09:29:23.924019: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
2021-11-05 09:29:26.722732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-11-05 09:29:26.743586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:26.743766: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:26.750762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:26.753345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:26.754543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:26.759512: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:26.762918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:26.769663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:26.769897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-11-05 09:29:26.790122: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-11-05 09:29:26.790623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:26.792930: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:26.793428: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:26.793950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:26.794570: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:26.796102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:26.796593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:26.796842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:26.797617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-11-05 09:29:26.815480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-11-05 09:29:26.846567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:26.846719: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:26.852704: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:26.855418: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:26.856899: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:26.861734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:26.865306: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:26.871959: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:26.872153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-11-05 09:29:26.891000: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-11-05 09:29:26.891435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1060 3GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 9 deviceMemorySize: 3.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021-11-05 09:29:26.893670: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-11-05 09:29:26.894120: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:29:26.894616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-11-05 09:29:26.895605: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-11-05 09:29:26.896034: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-11-05 09:29:26.896515: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-11-05 09:29:26.897017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:29:26.897614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2021-11-05 09:29:27.339607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-05 09:29:27.339724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2021-11-05 09:29:27.342275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2021-11-05 09:29:27.342940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2102 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-11-05 09:29:27.446993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-05 09:29:27.447121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2021-11-05 09:29:27.449601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2021-11-05 09:29:27.450239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2102 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Actor0 Start!
Learner Start!
2021-11-05 09:34:08.517594: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-11-05 09:34:08.786268: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-11-05 09:34:09.754327: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. This message will be only logged once.
actor0   Train 5276, Time: 20.05m, Reward    :  -21.00 -  -20.00 (ave:  -20.87), nb_steps: 24601
weight save, ave reward:-21.0000
learner  Train 5277, Time: 20.00m, TestReward:  -21.00 -  -21.00 (ave:  -21.00)
Traceback (most recent call last):
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\multiprocessing\queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\multiprocessing\queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "..\agent\agent57.py", line 398, in learner_run
    runner.train()
  File "..\agent\agent57.py", line 512, in train
    d["int"] = self.learner.actval_int_model.get_weights()
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\keras\engine\network.py", line 504, in get_weights
    return K.batch_get_value(weights)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\keras\backend\tensorflow_backend.py", line 2939, in batch_get_value
    return tf_keras_backend.batch_get_value(ops)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in batch_get_value
    return [x.numpy() for x in tensors]
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in <listcomp>
    return [x.numpy() for x in tensors]
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 582, in numpy
    return self.read_value().numpy()
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\framework\ops.py", line 943, in numpy
    return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 30.3 MiB for an array with shape (7760, 1024) and data type float32

Learning End. Train Count:7749
Traceback (most recent call last):
  File "..\agent\agent57.py", line 421, in learner_run
    callbacks.on_dis_learner_end(runner)
  File "..\agent\agent57.py", line 854, in on_dis_learner_end
    callback.on_dis_learner_end(learner)
  File "..\agent\callbacks.py", line 535, in on_dis_learner_end
    learner.save_weights(path, self.save_overwrite, save_memory=self.save_memory)
  File "..\agent\agent57.py", line 535, in save_weights
    self.learner.save_weights(filepath, overwrite, save_memory)
  File "..\agent\learner.py", line 157, in save_weights
    d["weights_int"] = self.actval_int_model.get_weights()
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\keras\engine\network.py", line 504, in get_weights
    return K.batch_get_value(weights)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\keras\backend\tensorflow_backend.py", line 2939, in batch_get_value
    return tf_keras_backend.batch_get_value(ops)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in batch_get_value
    return [x.numpy() for x in tensors]
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in <listcomp>
    return [x.numpy() for x in tensors]
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 582, in numpy
    return self.read_value().numpy()
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\tensorflow_core\python\framework\ops.py", line 943, in numpy
    return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 30.3 MiB for an array with shape (7760, 1024) and data type float32

done, took 2013.848 seconds
done, took 33.565 minutes
Traceback (most recent call last):
  File "atari_pong.py", line 234, in <module>
    run_agent57(enable_train=True)
  File "atari_pong.py", line 210, in run_agent57
    movie_save=False,
  File "..\agent\main_runner.py", line 170, in run_gym_agent57
    log.drawGraph("train")
  File "..\agent\callbacks.py", line 812, in drawGraph
    fig = plt.figure()
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\matplotlib\pyplot.py", line 546, in figure
    **kwargs)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\matplotlib\backend_bases.py", line 3337, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\matplotlib\backends\_backend_tk.py", line 892, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure, master=window)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\site-packages\matplotlib\backends\_backend_tk.py", line 203, in __init__
    master=self._tkcanvas, width=w, height=h)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\tkinter\__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Rob\Anaconda2\envs\agent57\lib\tkinter\__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: not enough free memory for image buffer

**Comment by pocokhc** [comment]
Hi,

There are several ways to avoid memory errors, but all come at a trade-off with learning accuracy.

Reduce the batch size ("batch_size": 16 → 2 or 4 or 8)
Reduce the number of input frames ("input_sequence": 4 → 1)
Reduce the number of hidden layer units ("dense_units_num": 256 → 128 or 64 or 32 or 16)
Do not use LSTM. LSTMs use a lot of memory. ("Lstm_type": LstmType.STATELESS → LstmType.NONE)

If you create a model that makes NN smaller, memory will be reduced.
